### ISSUE TITLE
minidoc.txt

### ISSUE THREAD

**Issue by lifelike** [AnimatorPro/Animator-Pro#19]
There is a very useful file in the binary download called minidoc.txt that documents a lot of things in the application even if it is written for some early version of Video Paint, so not everything is 100 % accurate. It is still the best documentation I have been able to find so far, and I think it could be useful to also include in the source code repo or even the wiki if that is not a problem with rights or something.

It would make sense to mention it in the readme as well.

**Comment by lifelike** [comment]
I could spend a few minutes (or hours) working it into the wiki if that sounds interesting. At least get the original text in there, split up into smaller pages perhaps, and do a first attempt att fixing things that are no longer true. Unless there IS some newer document it would be better to use.

**Comment by Breton** [comment]
not a bad idea, there's a couple other documents worth noting as well.
https://github.com/AnimatorPro/Animator-Pro/blob/master/text/v/GAMES
https://github.com/AnimatorPro/Animator-Pro/blob/master/text/v/MINIDOC.ASC
https://github.com/AnimatorPro/Animator-Pro/blob/b63d1d862ec6ab45db776e69d58c970e7000e030/Pristine-Pro/DOC/KEYEQUIV.DOC

in addition the archive.org version says it has some documentation with it that I haven't had a chance to look at yet 

https://archive.org/details/animatorpro

**Comment by lifelike** [comment]
I can't judge if there is some possible copyright infringement going on, but the aadocs.zip file on archive is definitely what I would recommend to anyone interested in learning how to use animator at this point.

MINIDOC.ASC looks like it is the same as the bundled minidoc.txt. I just did not spot it with that name. So it is included. Might still be good to link to. Or just drop this issue.
